export enum RECIPES_ACTION_TYPES {
  GET_RECIPES = "RECIPES/GET_RECIPES",
  ADD_RECIPE = "RECIPES/ADD_RECIPE",
  REMOVE_RECIPE = "RECIPES/REMOVE_RECIPE",
  EDIT_RECIPE = "RECIPES/EDIT_RECIPE",
}

export enum USER_ACTION_TYPES {
  GET_USER = "USER/GET_USER",
  UPDATE_USER = "USER/UPDATE_USER",
}

export enum TRANSACTIONS_ACTION_TYPES {
  GET_TRANSACTIONS = "TRANSACTIONS/GET_TRANSACTIONS",
  ADD_TRANSACTION = "TRANSACTIONS/ADD_TRANSACTION",
}
